# Generated by Django 6.0.4 on 2026-05-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_guest_id_cartitem_updated_at_and_more'),
        ('products', '0002_product_is_deleted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('product', 'size', 'color')},
        ),
    ]
