# Generated by Django 6.0.4 on 2026-05-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Card', 'Card'), ('UPI', 'UPI'), ('COD', 'COD')], default='UPI', max_length=20, null=True),
        ),
    ]
