# Generated by Django 6.0.4 on 2026-05-09 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.PositiveIntegerField(help_text='Amount in paise (₹1 = 100 paise)')),
                ('amount_refunded', models.PositiveIntegerField(default=0, help_text='Refunded amount in paise')),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('attempted', 'Attempted'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='created', max_length=30)),
                ('method', models.CharField(blank=True, max_length=50, null=True)),
                ('card_id', models.CharField(blank=True, max_length=100, null=True)),
                ('card_network', models.CharField(blank=True, max_length=50, null=True)),
                ('card_issuer', models.CharField(blank=True, max_length=100, null=True)),
                ('card_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('card_type', models.CharField(blank=True, max_length=20, null=True)),
                ('upi_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fee', models.PositiveIntegerField(default=0, help_text='Razorpay fee in paise')),
                ('tax', models.PositiveIntegerField(default=0, help_text='GST on Razorpay fee in paise')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_description', models.CharField(blank=True, max_length=255, null=True)),
                ('error_source', models.CharField(blank=True, max_length=100, null=True)),
                ('error_step', models.CharField(blank=True, max_length=100, null=True)),
                ('error_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_webhook_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='razorpay_payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Razorpay Payment',
                'verbose_name_plural': 'Razorpay Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['razorpay_order_id'], name='payments_ra_razorpa_704caf_idx'), models.Index(fields=['razorpay_payment_id'], name='payments_ra_razorpa_3677fd_idx'), models.Index(fields=['status'], name='payments_ra_status_8ece98_idx')],
            },
        ),
    ]
