# Generated by Django 6.0.4 on 2026-04-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], max_length=20)),
            ],
        ),
    ]
